#!/usr/bin/env python3
"""Post-processing for Armada II through vkBasalt -- bloom, for now.

    postfx.py --on                  write the config, prove it compiles, enable for the game
    postfx.py --set                 rewrite the config only (no Heroic change needed)
        --intensity F               bloom strength           (default 0.08)
        --threshold F               how bright a pixel must be to bloom (default 6.0)
    postfx.py --off                 disable for the game (config left in place)
    postfx.py --status              what is installed and enabled
    postfx.py --check               read vkBasalt's log from the last launch
    postfx.py --export DIR          write the files the release package carries, for
                                    vkBasalt and for ReShade (Windows); needs no layer

In game, **Home toggles the effect on and off** -- the only A/B this project has had
that needs no relaunch.  vkBasalt reads its config when the swapchain is created, so
a --set takes effect on the next launch, not live.

Needs the layer: postfx/vkbasalt/build.sh.  --on and --off edit Heroic's GamesConfig,
which Heroic rewrites from memory on exit, so they refuse while Heroic is running --
the same rule, for the same reason, as platform/dxvk-logging.py.

Why these defaults, measured rather than chosen: MagicBloom's own defaults
(threshold 2, intensity 1) were built for a lit 3D scene.  Run over a real frame of this
game (approximated in ImageMagick, pyramid and tonemap included) they lift the mean by
123/255 and touch 99.7% of pixels -- the frame goes milky.  The threshold is a POWER
(pow(c, t)), so it decides WHAT blooms and the intensity decides how much:

    threshold 6, intensity 0.1:  latinum +22.5/255, fog of war +0.7, HUD +3.8
    threshold 4, intensity 0.1:  latinum +27.2/255, fog of war +6.5, HUD +6.3

At 6 the bloom lands on what already clips (the additive sprites) and leaves the grey
shroud alone, 31:1; at 4 that selectivity falls to 4:1 and the shroud hazes over.
The first launch ran at 0.05 (half the stronger row); the user raised it once to 0.08
and kept it -- accepted in game, 2026-09-23.  That is the default now.

The HUD is part of the frame vkBasalt sees -- a post-process layer runs on the final
image, UI and all -- so bright UI elements can bloom too.  A high threshold is also
what keeps that small.
"""
import argparse
import importlib.util
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SHARE = os.path.join(os.environ.get('XDG_DATA_HOME', os.path.expanduser('~/.local/share')), 'a2-vkbasalt')
SHADERS = os.path.join(SHARE, 'Shaders')
TEXTURES = os.path.join(SHARE, 'Textures')
WRAPPER = os.path.join(SHARE, 'A2Bloom.fx')
CONF = os.path.join(SHARE, 'vkBasalt.conf')
LOG = os.path.join(SHARE, 'vkBasalt.log')
FXCHECK = os.path.expanduser('~/.local/lib/a2-vkbasalt/fxcheck')
MANIFEST = os.path.join(os.environ.get('XDG_DATA_HOME', os.path.expanduser('~/.local/share')),
                        'vulkan/implicit_layer.d/vkBasalt.a2.x86.json')
# The accepted defaults (see the docstring).  --export ships them in the release package.
INTENSITY = 0.08
THRESHOLD = 6.0

# A fixed identifier, not a path: installed configs carry it.  It predates the move to
# postfx/; keep it.
MARKER = '# generated by tools/postfx.py'

# Everything vkBasalt needs, set per game in Heroic -- never globally.  The layer's
# manifest makes it inert without ENABLE_VKBASALT=1.
ENV = {
    'ENABLE_VKBASALT': '1',
    'VKBASALT_CONFIG_FILE': CONF,
    'VKBASALT_LOG_FILE': LOG,
    'VKBASALT_LOG_LEVEL': 'info',
}

# Reuse Heroic's config handling rather than re-derive it (the enviromentOptions typo,
# the prefix match, the running check).
_spec = importlib.util.spec_from_file_location('dxvk_logging', os.path.join(HERE, '..', 'platform', 'dxvk-logging.py'))
heroic = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(heroic)


# ------------------------------------------------------------------ config

WRAPPER_SRC = """\
{marker}
// MagicBloom (luluco250, MIT, reshade-shaders legacy branch) with the two features an
// RTS camera does not want switched off at compile time:
//   NOADAPT -- eye adaptation rescales the bloom by average frame brightness, so it
//              would pulse as the camera pans between empty space and a nebula.
//   NODIRT  -- the lens-dirt overlay; there is no lens.
// These are preprocessor switches, which vkBasalt.conf cannot set, hence this file.
#define MAGICBLOOM_NOADAPT 1
#define MAGICBLOOM_NODIRT 1
#include "MagicBloom.fx"
"""


def conf_text(intensity, threshold, share=None, header=None):
    # vkBasalt's parser drops spaces outside quotes and treats '#' as a comment
    # anywhere, so every path is quoted and none of them may contain '#'.  They also
    # may not contain spaces in practice (the log warns about it), which is why none of
    # this lives in the game directory: "Star Trek Armada II".
    # share= puts the three files under another directory (--export's placeholder).
    wrapper, shaders, textures = (WRAPPER, SHADERS, TEXTURES) if share is None else (
        share + '/A2Bloom.fx', share + '/Shaders', share + '/Textures')
    return '\n'.join((header or [
        MARKER,
        '# Re-run postfx/postfx.py --set to change; --off to disable.  Home toggles in game.',
    ]) + [
        '',
        'effects = bloom',
        'bloom = "%s"' % wrapper,
        'reshadeIncludePath = "%s"' % shaders,
        'reshadeTexturePath = "%s"' % textures,
        'depthCapture = off',
        'toggleKey = Home',
        'enableOnLaunch = True',
        '',
        '# pow(colour, threshold) * intensity feeds the blur -- see postfx.py.',
        'fBloom_Intensity = %g' % intensity,
        'fBloom_Threshold = %g' % threshold,
        '',
    ])


def fxcheck():
    """Compile the wrapper exactly as vkBasalt will.  Returns the settable names."""
    if not os.path.exists(FXCHECK):
        sys.exit('fxcheck missing -- run postfx/vkbasalt/build.sh first')
    r = subprocess.run([FXCHECK, WRAPPER, SHADERS, '3440', '1440'], capture_output=True, text=True)
    if r.returncode != 0:
        sys.stdout.write(r.stdout + r.stderr)
        sys.exit('refusing: the effect does not compile, so it would be silently absent in game')
    for line in r.stdout.splitlines():
        if line.startswith(('technique', 'loads', 'OK')):
            print('    ' + line)
    loads = re.findall(r'^loads\s+(\S+)', r.stdout, re.M)
    for tex in loads:
        if not os.path.exists(os.path.join(TEXTURES, tex)):
            sys.exit('refusing: the effect loads %s, which is not in %s' % (tex, TEXTURES))
    return set(re.findall(r'^settable\s+(\S+)', r.stdout, re.M))


def write_config(intensity, threshold):
    if not os.path.isdir(SHADERS):
        sys.exit('no shaders in %s -- run postfx/vkbasalt/build.sh first' % SHADERS)
    with open(WRAPPER, 'w') as fh:
        fh.write(WRAPPER_SRC.format(marker='// ' + MARKER[2:]))
    text = conf_text(intensity, threshold)

    print('compiling %s:' % os.path.basename(WRAPPER))
    settable = fxcheck()
    # Every shader key in the config must be one the compiled effect exposes.  An
    # unknown key is ignored without a word, so a typo would read as "no change".
    wanted = re.findall(r'^(f[A-Z]\w+|i[A-Z]\w+)\s*=', text, re.M)
    missing = [k for k in wanted if k not in settable]
    if missing:
        sys.exit('refusing: %s not settable in this effect (it exposes: %s)'
                 % (', '.join(missing), ', '.join(sorted(settable))))
    print('    keys ok: %s' % ', '.join(wanted))

    with open(CONF, 'w') as fh:
        fh.write(text)
    print('wrote %s  (intensity %g, threshold %g)' % (CONF, intensity, threshold))


def export(out):
    """The release package's bloom files: the same effect and settings, three ways."""
    os.makedirs(out, exist_ok=True)
    files = {
        'A2Bloom.fx': WRAPPER_SRC.format(marker='// Armada II Refit: postfx/postfx.py --export'),
        # install.sh --bloom replaces @BLOOM@ with where it put the shaders.
        'vkBasalt.conf.in': conf_text(INTENSITY, THRESHOLD, share='@BLOOM@', header=[
            '# Armada II Refit bloom through vkBasalt (postfx/postfx.py --export).',
            '# Home toggles it in game.']),
        # ReShade on Windows sets the two MagicBloom switches in the preset, so it needs
        # no wrapper.  Home is ReShade's own overlay key; its effect toggle is set in
        # the overlay.
        'A2Bloom.ini': '\n'.join([
            'PreprocessorDefinitions=MAGICBLOOM_NOADAPT=1,MAGICBLOOM_NODIRT=1',
            'Techniques=MagicBloom@MagicBloom.fx',
            'TechniqueSorting=MagicBloom@MagicBloom.fx',
            '',
            '[MagicBloom.fx]',
            'fBloom_Intensity=%f' % INTENSITY,
            'fBloom_Threshold=%f' % THRESHOLD,
            '',
        ]),
    }
    for name, text in files.items():
        with open(os.path.join(out, name), 'w', newline='\r\n' if name.endswith('.ini') else '\n') as f:
            f.write(text)
        print(os.path.join(out, name))


# ------------------------------------------------------------------ heroic

def set_env(on):
    if heroic.heroic_running():
        sys.exit('refusing: Heroic is running and rewrites GamesConfig on exit.  '
                 'Quit it fully (tray icon included) and re-run.')
    path, data, key = heroic.find_config()
    env = heroic.env_list(data[key])
    env[:] = [e for e in env if e.get('key') not in ENV]
    if on:
        env.extend({'key': k, 'value': v} for k, v in ENV.items())
    import json
    tmp = path + '.tmp'
    with open(tmp, 'w') as fh:
        json.dump(data, fh, indent=2)
    os.replace(tmp, path)
    print('%s vkBasalt in %s' % ('enabled' if on else 'disabled', path))


def enabled_env():
    path, data, key = heroic.find_config()
    return {e['key']: e.get('value') for e in heroic.env_list(data[key]) if e.get('key') in ENV}


# ------------------------------------------------------------------ status / check

def status():
    print('layer     %s' % ('installed' if os.path.exists(MANIFEST) else 'MISSING -- postfx/vkbasalt/build.sh'))
    if os.path.exists(CONF):
        vals = dict(re.findall(r'^(fBloom_\w+)\s*=\s*(\S+)', open(CONF).read(), re.M))
        print('config    %s  %s' % (CONF, '  '.join('%s=%s' % kv for kv in sorted(vals.items()))))
    else:
        print('config    none')
    env = enabled_env()
    if env.get('ENABLE_VKBASALT') == '1':
        print('heroic    ENABLED for Armada II')
    elif env:
        print('heroic    partially set: %s' % env)
    else:
        print('heroic    off')


def check():
    if not os.path.exists(LOG):
        sys.exit('no log at %s -- the layer never loaded (or the game has not been launched '
                 'since --on).  If ENABLE_VKBASALT is set, the loader did not find the layer.' % LOG)
    text = open(LOG, errors='replace').read()
    print('log: %s (%d bytes)' % (LOG, len(text)))
    m = re.search(r'config file: (.*)', text)
    print('  config read  %s' % (m.group(1) if m else 'NONE -- vkBasalt found no config'))
    errs = [l for l in text.splitlines() if re.search(r'\berr', l, re.I)]
    if errs:
        print('  ERRORS:')
        for l in errs[:20]:
            print('    ' + l)
    else:
        print('  no errors logged')
    for l in text.splitlines():
        if re.search(r'fBloom_|effects =|swapchain|reshade', l, re.I):
            print('    ' + l.strip())


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument('--on', action='store_true')
    g.add_argument('--set', action='store_true')
    g.add_argument('--off', action='store_true')
    g.add_argument('--status', action='store_true')
    g.add_argument('--check', action='store_true')
    g.add_argument('--export', metavar='DIR')
    ap.add_argument('--intensity', type=float, default=INTENSITY)
    ap.add_argument('--threshold', type=float, default=THRESHOLD)
    a = ap.parse_args()

    if a.export:
        return export(a.export)

    if a.status:
        return status()
    if a.check:
        return check()
    if a.off:
        return set_env(False)
    if not os.path.exists(MANIFEST):
        sys.exit('layer not installed -- run postfx/vkbasalt/build.sh first')
    if a.on and heroic.heroic_running():
        # Check BEFORE writing anything, so a refusal leaves nothing half-done.
        sys.exit('refusing: Heroic is running and rewrites GamesConfig on exit.  '
                 'Quit it fully (tray icon included) and re-run.')
    write_config(a.intensity, a.threshold)
    if a.on:
        set_env(True)
        print('\nLaunch the game.  Home toggles bloom.  Afterwards: postfx/postfx.py --check')


if __name__ == '__main__':
    main()
