#!/usr/bin/env bash
# Write dxvk.conf beside Armada2.exe -- global renderer settings that apply to every
# texture and model at once.
#
#   renderer-config.sh              stage 1: anisotropic filtering only (the default)
#   renderer-config.sh --stage N    1 = AF, 2 = + mip LOD bias, 3 = + seamless cubes
#   renderer-config.sh --bias N     stage 2's LOD bias (default -0.5; less negative is
#                                   milder -- try -0.25 if the map shimmers on scroll)
#   renderer-config.sh --show       print what is installed now
#   renderer-config.sh --remove     delete dxvk.conf -- complete revert
#
# Stages are CUMULATIVE and deliberately separate: this project's method is one change
# at a time so that a bad result is attributable, and three keys at once is not.
# Judge each stage in game before raising it.  See SETUP.md, "Renderer-side
# enhancements", for why each key is here and what it is expected to do.
#
# Nothing else in the game directory is touched.  dxvk.conf does not exist in a stock
# install, so there is no backup to keep: removing the file restores stock exactly.
#
# Verified against DXVK 3.1.1, the version Heroic deploys.  Every key below was read out
# of that build's d3d9.dll -- see --verify-keys.
set -euo pipefail

GAME="${A2_GAME:-${A2_GAME_DIR:-/home/cedric/Games/Heroic/Star Trek Armada II}}"
CONF="$GAME/dxvk.conf"
MARKER="# generated by postfx/renderer-config.sh"

stage=1
action=install
force=0
# Stage 2's mip LOD bias.  -0.5 is the conservative end.  The failure mode of a
# negative bias is shimmer on movement rather than blur when still, and in this game it
# shows on the billboard layer first -- so if the map crawls while scrolling, halve this
# before abandoning the stage.  Below about -1.0 it aliases whatever AF is doing.
bias="${A2_LOD_BIAS:--0.5}"

while [ $# -gt 0 ]; do
    case "$1" in
        --stage)  stage="$2"; shift ;;
        --bias)   bias="$2"; shift ;;
        --show)   action=show ;;
        --remove) action=remove ;;
        --verify-keys) action=verify ;;
        --force)  force=1 ;;
        -h|--help) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
    shift
done

[ -d "$GAME" ] || { echo "game directory not found: $GAME" >&2; exit 1; }

case "$stage" in 1|2|3) ;; *) echo "stage must be 1, 2 or 3" >&2; exit 2 ;; esac

# ---------------------------------------------------------------- show / remove

if [ "$action" = show ]; then
    if [ ! -f "$CONF" ]; then
        echo "no dxvk.conf in $GAME -- stock renderer settings"
        exit 0
    fi
    if ! grep -qF "$MARKER" "$CONF"; then
        echo "dxvk.conf exists but was NOT written by this script:"
        sed 's/^/    /' "$CONF"
        exit 0
    fi
    echo "dxvk.conf: stage $(sed -n 's/^# stage: \([0-9]\).*/\1/p' "$CONF")"
    grep -E '^[a-z0-9]+\.' "$CONF" | sed 's/^/    /'
    exit 0
fi

if [ "$action" = remove ]; then
    if [ ! -f "$CONF" ]; then
        echo "no dxvk.conf in $GAME -- nothing to remove"
        exit 0
    fi
    if ! grep -qF "$MARKER" "$CONF" && [ "$force" != 1 ]; then
        echo "refusing: $CONF was not written by this script." >&2
        echo "Inspect it, then re-run with --force if you are sure." >&2
        exit 1
    fi
    rm -f "$CONF"
    echo "removed $CONF -- renderer is back to stock"
    exit 0
fi

# ---------------------------------------------------------------- verify keys

# Confirm every key we are about to write is actually honoured by the DXVK build that
# Heroic deploys.  A key DXVK does not know is silently ignored, so a typo here would
# read in game as "the setting did nothing" -- the same class of silent failure that
# ImageMagick's TGA origin handling caused on the texture side.
# Check against the d3d9.dll that ACTUALLY LOADS, which since the chain moved into the
# game directory is the one sitting beside Armada2.exe -- Proton's DXVK, not the build
# Heroic keeps in its tools directory.  Verifying against the wrong build is how a key
# the live DXVK does not know would still be reported "ok"; all four happen to exist in
# both, but that is luck, not a guarantee.
dxvk_dll() {
    local root="$HOME/.config/heroic/tools/dxvk" d name
    if [ -f "$GAME/d3d9.dll" ]; then
        echo "$GAME/d3d9.dll"
        return 0
    fi
    if [ -r "$root/latest_dxvk" ]; then
        name=$(tr -d '[:space:]' < "$root/latest_dxvk")
        [ -n "$name" ] && [ -f "$root/$name/x32/d3d9.dll" ] && { echo "$root/$name/x32/d3d9.dll"; return 0; }
    fi
    d=$(find "$root" -maxdepth 1 -type d -name 'dxvk-*' 2>/dev/null | sort -V | tail -1 || true)
    [ -n "$d" ] && [ -f "$d/x32/d3d9.dll" ] && echo "$d/x32/d3d9.dll"
}

verify_keys() {
    local dll missing=0 k blob
    dll=$(dxvk_dll || true)
    if [ -z "${dll:-}" ]; then
        echo "  (no Heroic DXVK build found -- skipping key verification)"
        return 0
    fi
    # Name what was actually checked. Deriving a label from the path's grandparent
    # printed "Heroic" for a DLL in the game directory, which is both wrong and the
    # kind of wrong that reads as right.
    if [ "$dll" = "$GAME/d3d9.dll" ]; then
        echo "  against the d3d9.dll in the game directory (the one that loads)"
    else
        echo "  against $(basename "$(dirname "$(dirname "$dll")")") (not in the chain)"
    fi

    # Read the DLL's strings ONCE into a variable and match with bash's own pattern
    # test.  Do NOT write this as `strings ... | grep -qxF "$k"`: grep -q exits on the
    # first match, strings then dies of SIGPIPE, and under `set -o pipefail` that makes
    # the pipeline report failure even though the key WAS found -- so every key reads as
    # MISSING.  Same family as the `read -r ... < <(...)` trap in CLAUDE.md.
    blob=$'\n'"$(strings -n 5 "$dll")"$'\n'

    for k in "$@"; do
        if [[ $blob == *$'\n'"$k"$'\n'* ]]; then
            echo "    ok      $k"
        else
            echo "    MISSING $k"
            missing=1
        fi
    done
    return $missing
}

keys_for_stage() {
    echo d3d9.samplerAnisotropy
    [ "$1" -ge 2 ] && { echo d3d9.samplerLodBias; echo d3d9.clampNegativeLodBias; }
    [ "$1" -ge 3 ] && echo d3d9.seamlessCubes
    return 0
}

if [ "$action" = verify ]; then
    echo "verifying stage $stage keys:"
    mapfile -t ks < <(keys_for_stage "$stage")
    verify_keys "${ks[@]}"
    exit $?
fi

# ---------------------------------------------------------------- install

if [ -f "$CONF" ] && ! grep -qF "$MARKER" "$CONF" && [ "$force" != 1 ]; then
    echo "refusing: $CONF already exists and was not written by this script." >&2
    echo "Inspect it, then re-run with --force to overwrite." >&2
    exit 1
fi

echo "verifying stage $stage keys:"
mapfile -t ks < <(keys_for_stage "$stage")
verify_keys "${ks[@]}" || { echo "aborting: DXVK does not know one of these keys" >&2; exit 1; }

{
    echo "$MARKER"
    echo "# stage: $stage   (re-run with --stage N to change; --remove to revert)"
    echo "# Why each key is here: SETUP.md, \"Renderer-side enhancements\"."
    echo "#"
    echo "# Measuring aid, deliberately NOT set here so it cannot be left on:"
    echo "#     DXVK_HUD=fps,frametimes"
    echo

    echo "# Stage 1 -- force anisotropic filtering."
    echo "# dxcfg.ini asks for 'application', i.e. whatever a 2001 renderer requests,"
    echo "# which is likely none.  In a top-down RTS every hull and every planet is drawn"
    echo "# at a steep angle to the camera, so all of it blurs along the axis of"
    echo "# foreshortening under plain trilinear."
    echo "d3d9.samplerAnisotropy = 16"

    if [ "$stage" -ge 2 ]; then
        echo
        echo "# Stage 2 -- bias mip selection toward the sharper level."
        echo "# There is now 1024-2048 art under an oblique camera and trilinear picks a"
        echo "# blurrier mip than that art can support.  Only safe with AF already on:"
        echo "# without it a negative bias aliases rather than sharpens."
        echo "# Failure mode is shimmer on movement, not blur when still.  If the map"
        echo "# crawls while scrolling, halve this (--bias) before abandoning the stage."
        echo "d3d9.samplerLodBias = $bias"
        echo "d3d9.clampNegativeLodBias = False"
    fi

    if [ "$stage" -ge 3 ]; then
        echo
        echo "# Stage 3 -- filter across cube-map face edges."
        echo "# Many maps bind a .sod cube model for the skybox, and a face-edge seam gets"
        echo "# more visible at 2048/face, not less."
        echo "d3d9.seamlessCubes = True"
    fi
} > "$CONF"

echo
echo "wrote $CONF (stage $stage):"
grep -E '^[a-z0-9]+\.' "$CONF" | sed 's/^/    /'
echo
echo "Next: launch, judge it, and only then raise the stage."
echo "Revert at any time with: $0 --remove"
