#!/usr/bin/env bash
# Armada II Refit -- install the release package into the game, on Linux (Wine/Proton).
#
#   ./install.sh [<game dir>]               install
#   ./install.sh --uninstall [<game dir>]   take all of it out again
#
# No choices to make: what can work here is installed, the rest is skipped and says why.
# First the prerequisites (prereqs.txt: the ASI loader with STA2WidescreenPatch), bundled
# in vendor/, each file only if missing. MSAA.asi goes in when DXVK's d3d8.dll is in the game directory (without DXVK the minimap goes
# black); bloom is set up when a vkBasalt layer is installed.
#
# The game directory is the one holding Armada2.exe: the argument, else this folder's
# parent if the package was unzipped into the game, else $A2_GAME, else Heroic's
# default for the GOG release. This is the release zip's installer, and it
# stands alone: it needs nothing from the repository. (The repository's own ./install
# builds from source and installs the asset layers too.)
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
action=install game=""
while [ $# -gt 0 ]; do
    case "$1" in
        --uninstall) action=uninstall ;;
        -h|--help)   sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        -*)          echo "unknown option: $1" >&2; exit 2 ;;
        *)           game="$1" ;;
    esac
    shift
done
# Unzipped into the game directory itself: that is the one.
if [ -z "$game" ] && [ -f "$here/../Armada2.exe" ]; then game="$here/.."; fi
game="${game:-${A2_GAME:-$HOME/Games/Heroic/Star Trek Armada II}}"
exe=$(ls "$game/Armada2.exe" "$game/armada2.exe" "$game/ARMADA2.EXE" 2>/dev/null | head -1 || true)
[ -n "$exe" ] || { echo "no Armada2.exe in $game -- pass the game directory as an argument" >&2; exit 1; }
game="$(cd "$game" && pwd)"

if pgrep -if 'armada2\.exe' >/dev/null 2>&1; then
    echo "Armada2.exe is running -- quit the game first" >&2; exit 1
fi

# Where bloom's files go. vkBasalt's config parser cannot take a space or a '#' in a
# path, which rules out the game directory ("Star Trek Armada II").
BLOOM="${XDG_DATA_HOME:-$HOME/.local/share}/armada2-refit-bloom"
DXVK_MARKER="# generated by tools/renderer-config.sh"   # dxvk.conf files we wrote
BLOOM_MARKER="# written by armada2-refit install.sh"

MANIFEST="$game/armada2-refit-prereqs.txt"   # what the prerequisites step added

is_proxy() { grep -q 'BinkProxy' "$1" 2>/dev/null; }
# DXVK by content, never by name: GOG puts a d3d8.dll there too.
is_dxvk() { grep -a -q -i 'dxvk' "$1" 2>/dev/null; }

# ------------------------------------------------------------------ uninstall

if [ "$action" = uninstall ]; then
    for n in HUD Menus MSAA QOL; do rm -f "$game/$n.asi" "$game/$n.ini" "$game/$n.log"; done
    if is_proxy "$game/binkw32.dll"; then
        if [ -f "$game/binkw32.dll.a2neb-backup" ]; then
            mv -f "$game/binkw32.dll.a2neb-backup" "$game/binkw32.dll"
            rm -f "$game/binkw32_orig.dll"
        elif [ -f "$game/binkw32_orig.dll" ]; then
            mv -f "$game/binkw32_orig.dll" "$game/binkw32.dll"
        else
            echo "binkw32.dll is the proxy and there is no stock copy -- restore it by hand" >&2
        fi
    fi
    rm -f "$game/BinkProxy.ini" "$game/BinkProxy.log"
    if [ -f "$game/dxvk.conf" ] && grep -qF "$DXVK_MARKER" "$game/dxvk.conf"; then
        rm -f "$game/dxvk.conf"
    fi
    # The prerequisites, newest record first; a file changed since is left, and said so.
    if [ -f "$MANIFEST" ]; then
        tac "$MANIFEST" | while read -r f sum; do
            [ -e "$game/$f" ] || continue
            if [ "$(sha256sum "$game/$f" | cut -d' ' -f1)" != "$sum" ]; then
                echo "  left $f: it changed since it was installed"; continue
            fi
            rm -f "$game/$f"
        done
        rm -f "$MANIFEST"
    fi
    if [ -f "$BLOOM/vkBasalt.conf" ] && grep -qF "$BLOOM_MARKER" "$BLOOM/vkBasalt.conf"; then
        rm -rf "$BLOOM"
        echo "removed $BLOOM -- also take ENABLE_VKBASALT and VKBASALT_CONFIG_FILE out of the launcher"
    fi
    echo "uninstalled from $game"
    exit 0
fi

(cd "$here" && sha256sum --quiet -c SHA256SUMS) || { echo "the package is damaged (SHA256SUMS)" >&2; exit 1; }
echo "installing into $game"

# ------------------------------------------------------------------ prerequisites

# The ASI loader and STA2WidescreenPatch (prereqs.txt), in vendor/<name>/ because their
# licence allows it. A file already in the game directory is never overwritten. What this
# adds is recorded in $MANIFEST with its hash, so --uninstall takes out only that, and
# only unchanged.
record() { echo "$1 $(sha256sum "$game/$1" | cut -d' ' -f1)" >> "$MANIFEST"; }

prereq() {   # name|version|author|licence|page|files
    local name ver author lic page files f
    IFS='|' read -r name ver author lic page files <<< "$1"
    f="${files%% *}"
    if [ -e "$game/$f" ]; then echo "  $name: already installed"; return 0; fi
    for f in $files; do
        [ -e "$game/$f" ] || { cp "$here/vendor/$name/$f" "$game/$f"; record "$f"; }
    done
    echo "  $name $ver -- $author; $lic"
    echo "      from $page"
}

echo "prerequisites:"
while IFS= read -r line; do [ -n "$line" ] && prereq "$line"; done < "$here/prereqs.txt"
echo "the mod:"

# ------------------------------------------------------------------ plugins

# A changed .ini is kept beside the new one, as <name>.ini.bak.
put() {   # file -- copy from the package into the game directory
    local f="$1" d="$game/$1"
    if [ -f "$d" ] && [ "${f##*.}" = ini ] && ! cmp -s "$here/game/$f" "$d"; then
        cp -p "$d" "$d.bak"; echo "  kept your old $f as $f.bak"
    fi
    cp "$here/game/$f" "$d"
    echo "  $f"
}

put HUD.asi; put HUD.ini
rm -f "$game/MenuScale.asi" "$game/MenuScale.ini"   # Menus.asi's old name; never both
put Menus.asi; put Menus.ini
put QOL.asi; put QOL.ini

if is_dxvk "$game/d3d8.dll"; then
    put MSAA.asi; put MSAA.ini
else
    rm -f "$game/MSAA.asi"
    echo "  MSAA.asi skipped: DXVK's d3d8.dll is not in the game directory"
fi

# The proxy forwards every call to the stock DLL as binkw32_orig.dll.
if ! is_proxy "$game/binkw32.dll"; then
    [ -f "$game/binkw32.dll" ] || { echo "no binkw32.dll in $game" >&2; exit 1; }
    cp -p "$game/binkw32.dll" "$game/binkw32.dll.a2neb-backup"
    cp -p "$game/binkw32.dll" "$game/binkw32_orig.dll"
fi
[ -f "$game/binkw32_orig.dll" ] || { echo "binkw32.dll is the proxy but binkw32_orig.dll is missing" >&2; exit 1; }
put binkw32.dll; put BinkProxy.ini

if [ -f "$game/dxvk.conf" ] && ! grep -qF "$DXVK_MARKER" "$game/dxvk.conf"; then
    echo "  dxvk.conf skipped: there is one already that this package did not write"
else
    put dxvk.conf
fi

# ------------------------------------------------------------------ bloom

# Needs a 32-bit vkBasalt layer (lib32-vkbasalt on Arch; or postfx/vkbasalt/build.sh in
# the repository) -- the game is a 32-bit process. Without one, bloom is skipped.
bloom=0
for d in "${XDG_DATA_HOME:-$HOME/.local/share}/vulkan/implicit_layer.d" \
         /etc/vulkan/implicit_layer.d /usr/share/vulkan/implicit_layer.d; do
    ls "$d"/*[Bb]asalt*.json >/dev/null 2>&1 && bloom=1
done

# The shaders are not ours to redistribute, so they come from upstream, pinned by commit
# and checked by hash (<sha256> <commit> <file>). Bloom is optional: a failure skips it.
fetch_shaders() {
    local sum commit file dst url
    while read -r sum commit file; do
        [ -n "$sum" ] || continue
        dst="$BLOOM/Shaders/$file"
        echo "$sum  $dst" | sha256sum --quiet -c - >/dev/null 2>&1 && continue
        url="https://raw.githubusercontent.com/crosire/reshade-shaders/$commit/Shaders/$file"
        if command -v curl >/dev/null; then curl -fsSL -o "$dst" "$url" || return 1
        else wget -qO "$dst" "$url" || return 1; fi
        echo "$sum  $dst" | sha256sum --quiet -c - >/dev/null 2>&1 || { rm -f "$dst"; return 1; }
    done < "$here/bloom/shaders.txt"
}

if [ "$bloom" = 0 ]; then
    echo "  bloom skipped: no vkBasalt layer installed (optional -- README.txt)"
else
    case "$BLOOM" in *' '*|*'#'*) bloom=0; echo "  bloom skipped: vkBasalt cannot read the path $BLOOM" ;; esac
fi
if [ "$bloom" = 1 ]; then
    mkdir -p "$BLOOM/Shaders" "$BLOOM/Textures"
    if fetch_shaders; then
        cp "$here/bloom/A2Bloom.fx" "$BLOOM/A2Bloom.fx"
        sed -e "s|@BLOOM@|$BLOOM|g" -e "1i$BLOOM_MARKER" "$here/bloom/vkBasalt.conf.in" > "$BLOOM/vkBasalt.conf"
        echo "  bloom, in $BLOOM"
    else
        bloom=0; echo "  bloom skipped: could not download its shaders from GitHub"
    fi
fi

# ------------------------------------------------------------------ what is left

# Wine prefers its own builtin DLLs; these make it load the game directory's.
overrides="winmm=n,b;d3d8=n,b"
if [ -e "$game/d3d9.dll" ]; then overrides="$overrides;d3d9=n,b"; fi
echo
echo "In the launcher (Heroic: Game settings -> Advanced -> Environment variables; Steam:"
echo "launch options, then %command%), set:"
echo "    WINEDLLOVERRIDES=$overrides"
if [ "$bloom" = 1 ]; then
    echo "and for bloom (Home toggles it in game):"
    echo "    ENABLE_VKBASALT=1"
    echo "    VKBASALT_CONFIG_FILE=$BLOOM/vkBasalt.conf"
fi
echo "Uninstall: $0 --uninstall \"$game\""
