<#
Armada II Refit -- install the release package into the game, on Windows.

  install.bat [<game dir>]                 install
  install.bat -Uninstall [<game dir>]      take all of it out again

No choices to make: what can work here is installed, the rest is skipped and says why.
First the prerequisites (prereqs.txt: the ASI loader with STA2WidescreenPatch, and Patch
Project 1.2.5), bundled or downloaded and hash-checked, each only if it is missing. MSAA.asi goes in when DXVK's d3d8.dll is in the
game directory -- without DXVK the minimap goes black. The bloom preset goes in when ReShade is installed for the game;
installing ReShade is optional and by hand (README.txt), then run this again.

The game directory is the one holding Armada2.exe: the argument, else this folder's
parent if the package was unzipped into the game, else the GOG install found in the
registry, else it asks. PowerShell 5.1 or later; install.bat runs it.
#>
param(
    [string]$GameDir = "",
    [switch]$Uninstall
)
$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$DxvkMarker = "# generated by tools/renderer-config.sh"   # dxvk.conf files we wrote

function Test-Game([string]$d) { $d -and (Test-Path -LiteralPath (Join-Path $d "Armada2.exe")) }

if (-not (Test-Game $GameDir)) {
    if ($GameDir) { throw "no Armada2.exe in $GameDir" }
    $parent = Split-Path -Parent $here
    if (Test-Game $parent) { $GameDir = $parent }
}
if (-not $GameDir) {
    foreach ($k in @("HKLM:\SOFTWARE\WOW6432Node\GOG.com\Games", "HKLM:\SOFTWARE\GOG.com\Games")) {
        if (-not (Test-Path $k)) { continue }
        foreach ($g in Get-ChildItem $k) {
            $p = Get-ItemProperty $g.PSPath
            if ($p.gameName -like "*Armada II*" -and (Test-Game $p.path)) { $GameDir = $p.path; break }
        }
        if ($GameDir) { break }
    }
}
if (-not $GameDir) { $GameDir = (Read-Host "Game directory (the folder with Armada2.exe)").Trim('"') }
if (-not (Test-Game $GameDir)) { throw "no Armada2.exe in $GameDir" }
$GameDir = (Resolve-Path -LiteralPath $GameDir).Path

if (Get-Process -Name armada2 -ErrorAction SilentlyContinue) { throw "Armada2.exe is running -- quit the game first" }

function G([string]$n) { Join-Path $GameDir $n }
$Manifest = G "armada2-refit-prereqs.txt"   # what the prerequisites step added
function Get-Sha([string]$f) { (Get-FileHash -Algorithm SHA256 -LiteralPath $f).Hash.ToLower() }
# DXVK by content, never by name: Patch Project and GOG each put a d3d8.dll there too.
function Test-Dxvk([string]$f) {
    (Test-Path -LiteralPath $f) -and
        ([Text.Encoding]::ASCII.GetString([IO.File]::ReadAllBytes($f)) -match "(?i)dxvk")
}
function Test-Proxy([string]$f) {
    (Test-Path -LiteralPath $f) -and (Select-String -LiteralPath $f -Pattern "BinkProxy" -SimpleMatch -Quiet)
}
function Test-OurDxvkConf {
    (Test-Path -LiteralPath (G "dxvk.conf")) -and
        (Select-String -LiteralPath (G "dxvk.conf") -Pattern $DxvkMarker -SimpleMatch -Quiet)
}

# ------------------------------------------------------------------ uninstall

if ($Uninstall) {
    foreach ($n in "HUD", "Menus", "MSAA") {
        foreach ($e in ".asi", ".ini", ".log") { Remove-Item -LiteralPath (G "$n$e") -ErrorAction SilentlyContinue }
    }
    if (Test-Proxy (G "binkw32.dll")) {
        if (Test-Path -LiteralPath (G "binkw32.dll.a2neb-backup")) {
            Move-Item -LiteralPath (G "binkw32.dll.a2neb-backup") (G "binkw32.dll") -Force
            Remove-Item -LiteralPath (G "binkw32_orig.dll") -ErrorAction SilentlyContinue
        } elseif (Test-Path -LiteralPath (G "binkw32_orig.dll")) {
            Move-Item -LiteralPath (G "binkw32_orig.dll") (G "binkw32.dll") -Force
        } else {
            Write-Warning "binkw32.dll is the proxy and there is no stock copy -- restore it by hand"
        }
    }
    # ReShadePreset.ini only if it is still ours, unchanged.
    if ((Test-Path -LiteralPath (G "ReShadePreset.ini")) -and
        (Get-FileHash -LiteralPath (G "ReShadePreset.ini")).Hash -eq (Get-FileHash -LiteralPath (Join-Path $here "bloom\A2Bloom.ini")).Hash) {
        Remove-Item -LiteralPath (G "ReShadePreset.ini")
    }
    foreach ($n in "BinkProxy.ini", "BinkProxy.log", "A2Bloom.ini") { Remove-Item -LiteralPath (G $n) -ErrorAction SilentlyContinue }
    if (Test-OurDxvkConf) { Remove-Item -LiteralPath (G "dxvk.conf") }
    # The prerequisites, newest record first; a file changed since is left, and said so.
    if (Test-Path -LiteralPath $Manifest) {
        $records = @(Get-Content -LiteralPath $Manifest)
        [array]::Reverse($records)
        foreach ($r in $records) {
            $how, $f, $sum, $backup = $r -split " "
            if (-not (Test-Path -LiteralPath (G $f))) { continue }
            if ((Get-Sha (G $f)) -ne $sum) { Write-Host "  left ${f}: it changed since it was installed"; continue }
            Remove-Item -LiteralPath (G $f)
            if ($how -eq "moved" -and (Test-Path -LiteralPath (G $backup))) { Move-Item -LiteralPath (G $backup) (G $f) }
        }
        Remove-Item -LiteralPath $Manifest
    }
    Write-Host "uninstalled from $GameDir"
    exit 0
}

foreach ($line in Get-Content -LiteralPath (Join-Path $here "SHA256SUMS")) {
    $sum, $file = $line -split "\s+\*?", 2
    if ((Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $here $file)).Hash -ne $sum) {
        throw "the package is damaged: $file does not match SHA256SUMS"
    }
}
Write-Host "installing into $GameDir"

# ------------------------------------------------------------------ prerequisites

# The ASI loader, STA2WidescreenPatch and Patch Project 1.2.5 (prereqs.txt). One whose
# licence allows it is in the zip, under vendor\<name>\ (its url is "-"); the others are
# downloaded from where their authors publish them, pinned by SHA-256.
# A file already in the game directory is never overwritten. What this adds is recorded
# in $Manifest with its hash, so -Uninstall takes out only that, and only unchanged.
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$work = Join-Path ([IO.Path]::GetTempPath()) ([Guid]::NewGuid())
New-Item -ItemType Directory $work | Out-Null
function Add-Record([string]$how, [string]$f, [string]$backup = "") {
    Add-Content -LiteralPath $Manifest ("$how $f $(Get-Sha (G $f)) $backup".Trim())
}
# The zip at $url, or a file with the same hash in the package's downloads\ folder.
function Get-Zip([string]$url, [string]$sum, [string]$out) {
    $dl = Join-Path $here "downloads"
    if (Test-Path -LiteralPath $dl) {
        foreach ($f in Get-ChildItem -LiteralPath $dl -File) {
            if ((Get-Sha $f.FullName) -eq $sum) { Copy-Item -LiteralPath $f.FullName $out; return $true }
        }
    }
    try { Invoke-WebRequest -UseBasicParsing -OutFile $out -Uri $url } catch { return $false }
    return ((Get-Sha $out) -eq $sum)
}

Write-Host "prerequisites:"
foreach ($line in Get-Content -LiteralPath (Join-Path $here "prereqs.txt")) {
    if (-not $line.Trim()) { continue }
    $name, $ver, $author, $lic, $page, $url, $sum, $members = $line -split "\|"
    $members = $members -split " "
    if (Test-Path -LiteralPath (G (Split-Path -Leaf $members[0]))) { Write-Host "  ${name}: already installed"; continue }
    if ($url -eq "-") {
        $x = Join-Path $here "vendor\$name"
    } else {
        $zip = Join-Path $work "$name.zip"
        if (-not (Get-Zip $url $sum $zip)) {
            throw "could not download $name $ver. Get it from $page, put the zip in $(Join-Path $here 'downloads') and run this again."
        }
        $x = Join-Path $work $name
        Expand-Archive -LiteralPath $zip -DestinationPath $x
    }
    foreach ($m in $members) {
        $b = Split-Path -Leaf $m; $src = Join-Path $x $m
        if ($b -eq "d3d8.dll" -and (Test-Path -LiteralPath (G "d3d8.dll"))) {
            if (Test-Dxvk (G "d3d8.dll")) {
                # DXVK keeps the slot; the proxy waits where platform/d3d8-chain.py keeps it.
                if (-not (Test-Path -LiteralPath (G "d3d8.dll.proxy-backup"))) {
                    Copy-Item -LiteralPath $src (G "d3d8.dll.proxy-backup"); Add-Record "added" "d3d8.dll.proxy-backup"
                }
            } elseif (-not (Test-Path -LiteralPath (G "d3d8.dll.gog-backup"))) {
                # GOG's d3d8to9: Patch Project's own instructions replace it.
                Move-Item -LiteralPath (G "d3d8.dll") (G "d3d8.dll.gog-backup")
                Copy-Item -LiteralPath $src (G "d3d8.dll"); Add-Record "moved" "d3d8.dll" "d3d8.dll.gog-backup"
            }
        } elseif (-not (Test-Path -LiteralPath (G $b))) {
            Copy-Item -LiteralPath $src (G $b); Add-Record "added" $b
        }
    }
    Write-Host "  $name $ver -- $author; $lic"
    Write-Host "      from $page"
}

Remove-Item -Recurse -Force $work

# STA2WidescreenPatch.asi needs Microsoft's Visual C++ runtime (VCRUNTIME140.dll), which
# almost every Windows has. Installing it takes administrator rights and an unpinned
# Microsoft download, so this only says where to get it.
$sysdir = if ([Environment]::Is64BitOperatingSystem) { "SysWOW64" } else { "System32" }
if (-not (Test-Path -LiteralPath (Join-Path $env:WINDIR "$sysdir\vcruntime140.dll"))) {
    Write-Warning ("the Visual C++ runtime (x86) is missing, and the widescreen patch needs it. " +
        "Install it from https://aka.ms/vs/17/release/vc_redist.x86.exe")
}
Write-Host "the mod:"

# ------------------------------------------------------------------ plugins

# A changed .ini is kept beside the new one, as <name>.ini.bak.
function Put([string]$f) {
    $src = Join-Path $here "game\$f"; $dst = G $f
    if ($f.EndsWith(".ini") -and (Test-Path -LiteralPath $dst) -and
        (Get-FileHash -LiteralPath $src).Hash -ne (Get-FileHash -LiteralPath $dst).Hash) {
        Copy-Item -LiteralPath $dst "$dst.bak" -Force
        Write-Host "  kept your old $f as $f.bak"
    }
    Copy-Item -LiteralPath $src $dst -Force
    Write-Host "  $f"
}

Put "HUD.asi"; Put "HUD.ini"
foreach ($n in "MenuScale.asi", "MenuScale.ini") { Remove-Item -LiteralPath (G $n) -ErrorAction SilentlyContinue }   # Menus.asi's old name
Put "Menus.asi"; Put "Menus.ini"

if (Test-Dxvk (G "d3d8.dll")) {
    Put "MSAA.asi"; Put "MSAA.ini"
} else {
    Remove-Item -LiteralPath (G "MSAA.asi") -ErrorAction SilentlyContinue
    Write-Host "  MSAA.asi skipped: DXVK's d3d8.dll is not in the game directory"
}

# The proxy forwards every call to the stock DLL as binkw32_orig.dll.
if (-not (Test-Proxy (G "binkw32.dll"))) {
    if (-not (Test-Path -LiteralPath (G "binkw32.dll"))) { throw "no binkw32.dll in $GameDir" }
    Copy-Item -LiteralPath (G "binkw32.dll") (G "binkw32.dll.a2neb-backup") -Force
    Copy-Item -LiteralPath (G "binkw32.dll") (G "binkw32_orig.dll") -Force
}
if (-not (Test-Path -LiteralPath (G "binkw32_orig.dll"))) { throw "binkw32.dll is the proxy but binkw32_orig.dll is missing" }
Put "binkw32.dll"; Put "BinkProxy.ini"

if ((Test-Path -LiteralPath (G "dxvk.conf")) -and -not (Test-OurDxvkConf)) {
    Write-Host "  dxvk.conf skipped: there is one already that this package did not write"
} else {
    Put "dxvk.conf"
}

# ------------------------------------------------------------------ bloom

# Only when ReShade is installed for the game: its setup leaves ReShade.ini beside the
# exe, and it finds shaders in reshade-shaders\Shaders there. They are not ours to
# redistribute, so any that are missing come from upstream, pinned by commit and checked
# by hash; ones already there (ReShade's own) are left alone. Bloom is optional: a
# failure skips it.
function Install-Bloom {
    $sh = G "reshade-shaders\Shaders"
    New-Item -ItemType Directory -Force -Path $sh | Out-Null
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    foreach ($line in Get-Content -LiteralPath (Join-Path $here "bloom\shaders.txt")) {
        if (-not $line.Trim()) { continue }
        $sum, $commit, $file = $line -split "\s+"
        $dst = Join-Path $sh $file
        if (Test-Path -LiteralPath $dst) { continue }
        $url = "https://raw.githubusercontent.com/crosire/reshade-shaders/$commit/Shaders/$file"
        Invoke-WebRequest -UseBasicParsing -OutFile $dst -Uri $url
        if ((Get-FileHash -Algorithm SHA256 -LiteralPath $dst).Hash -ne $sum) {
            Remove-Item -LiteralPath $dst; throw "download does not match: $file"
        }
    }
    Copy-Item -LiteralPath (Join-Path $here "bloom\A2Bloom.ini") (G "A2Bloom.ini") -Force
    # ReShade loads ReShadePreset.ini unless told otherwise, so with no preset of the
    # player's own, ours takes that name and bloom needs no step in the overlay.
    if (-not (Test-Path -LiteralPath (G "ReShadePreset.ini"))) {
        Copy-Item -LiteralPath (G "A2Bloom.ini") (G "ReShadePreset.ini")
        return $true
    }
    return $false
}
if (-not (Test-Path -LiteralPath (G "ReShade.ini"))) {
    Write-Host "  bloom skipped: ReShade is not installed (optional -- README.txt)"
} else {
    try {
        if (Install-Bloom) {
            Write-Host "  bloom, as ReShade's preset (ReShadePreset.ini)"
        } else {
            Write-Host "  A2Bloom.ini -- you have a ReShade preset already; pick this one in its overlay"
        }
    } catch {
        Write-Host "  bloom skipped: $($_.Exception.Message)"
    }
}

# ------------------------------------------------------------------ what is left

Write-Host ""
if (-not (Test-Path -LiteralPath (G "winmm.dll"))) {
    Write-Warning "no ASI loader (winmm.dll) in the game directory -- the plugins will not load."
}
Write-Host "Uninstall: install.bat -Uninstall `"$GameDir`""
