#!/usr/bin/env bash
# Armada II Refit -- install the release package into the game, on Linux (Wine/Proton).
#
#   ./install.sh [<game dir>]               install the plugins and dxvk.conf
#   ./install.sh --bloom [<game dir>]       also set up bloom through vkBasalt
#   ./install.sh --uninstall [<game dir>]   take all of it out again
#
#   --msaa / --no-msaa   MSAA.asi is installed only when DXVK's d3d8.dll is in the game
#                        directory (without DXVK the minimap goes black); these override
#
# The game directory is the one holding Armada2.exe: the argument, else this folder's
# parent if the package was unzipped into the game, else $A2_GAME, else Heroic's
# default for the GOG release. This is the release zip's installer, and it
# stands alone: it needs nothing from the repository. (The repository's own ./install
# builds from source and installs the asset layers too.)
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
action=install bloom=0 msaa=auto game=""
while [ $# -gt 0 ]; do
    case "$1" in
        --bloom)     bloom=1 ;;
        --uninstall) action=uninstall ;;
        --msaa)      msaa=1 ;;
        --no-msaa)   msaa=0 ;;
        -h|--help)   sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        -*)          echo "unknown option: $1" >&2; exit 2 ;;
        *)           game="$1" ;;
    esac
    shift
done
# Unzipped into the game directory itself: that is the one.
if [ -z "$game" ] && [ -f "$here/../Armada2.exe" ]; then game="$here/.."; fi
game="${game:-${A2_GAME:-$HOME/Games/Heroic/Star Trek Armada II}}"
exe=$(ls "$game/Armada2.exe" "$game/armada2.exe" "$game/ARMADA2.EXE" 2>/dev/null | head -1 || true)
[ -n "$exe" ] || { echo "no Armada2.exe in $game -- pass the game directory as an argument" >&2; exit 1; }
game="$(cd "$game" && pwd)"

if pgrep -if 'armada2\.exe' >/dev/null 2>&1; then
    echo "Armada2.exe is running -- quit the game first" >&2; exit 1
fi

# Where bloom's files go. vkBasalt's config parser cannot take a space or a '#' in a
# path, which rules out the game directory ("Star Trek Armada II").
BLOOM="${XDG_DATA_HOME:-$HOME/.local/share}/armada2-refit-bloom"
DXVK_MARKER="# generated by tools/renderer-config.sh"   # dxvk.conf files we wrote
BLOOM_MARKER="# written by armada2-refit install.sh"

is_proxy() { grep -q 'BinkProxy' "$1" 2>/dev/null; }

# ------------------------------------------------------------------ uninstall

if [ "$action" = uninstall ]; then
    for n in HUD Menus MSAA; do rm -f "$game/$n.asi" "$game/$n.ini" "$game/$n.log"; done
    if is_proxy "$game/binkw32.dll"; then
        if [ -f "$game/binkw32.dll.a2neb-backup" ]; then
            mv -f "$game/binkw32.dll.a2neb-backup" "$game/binkw32.dll"
            rm -f "$game/binkw32_orig.dll"
        elif [ -f "$game/binkw32_orig.dll" ]; then
            mv -f "$game/binkw32_orig.dll" "$game/binkw32.dll"
        else
            echo "binkw32.dll is the proxy and there is no stock copy -- restore it by hand" >&2
        fi
    fi
    rm -f "$game/BinkProxy.ini" "$game/BinkProxy.log"
    if [ -f "$game/dxvk.conf" ] && grep -qF "$DXVK_MARKER" "$game/dxvk.conf"; then
        rm -f "$game/dxvk.conf"
    fi
    if [ -f "$BLOOM/vkBasalt.conf" ] && grep -qF "$BLOOM_MARKER" "$BLOOM/vkBasalt.conf"; then
        rm -rf "$BLOOM"
        echo "removed $BLOOM -- also take ENABLE_VKBASALT and VKBASALT_CONFIG_FILE out of the launcher"
    fi
    echo "uninstalled from $game"
    exit 0
fi

# ------------------------------------------------------------------ plugins

(cd "$here" && sha256sum --quiet -c SHA256SUMS) || { echo "the package is damaged (SHA256SUMS)" >&2; exit 1; }
echo "installing into $game"

# A changed .ini is kept beside the new one, as <name>.ini.bak.
put() {   # file -- copy from the package into the game directory
    local f="$1" d="$game/$1"
    if [ -f "$d" ] && [ "${f##*.}" = ini ] && ! cmp -s "$here/game/$f" "$d"; then
        cp -p "$d" "$d.bak"; echo "  kept your old $f as $f.bak"
    fi
    cp "$here/game/$f" "$d"
    echo "  $f"
}

put HUD.asi; put HUD.ini
rm -f "$game/MenuScale.asi" "$game/MenuScale.ini"   # Menus.asi's old name; never both
put Menus.asi; put Menus.ini

if [ "$msaa" = auto ]; then
    if [ -f "$game/d3d8.dll" ]; then msaa=1; else msaa=0; fi
fi
if [ "$msaa" = 1 ]; then
    put MSAA.asi; put MSAA.ini
else
    rm -f "$game/MSAA.asi"
    echo "  MSAA.asi skipped: no d3d8.dll (DXVK) in the game directory (--msaa overrides)"
fi

# The proxy forwards every call to the stock DLL as binkw32_orig.dll.
if ! is_proxy "$game/binkw32.dll"; then
    [ -f "$game/binkw32.dll" ] || { echo "no binkw32.dll in $game" >&2; exit 1; }
    cp -p "$game/binkw32.dll" "$game/binkw32.dll.a2neb-backup"
    cp -p "$game/binkw32.dll" "$game/binkw32_orig.dll"
fi
[ -f "$game/binkw32_orig.dll" ] || { echo "binkw32.dll is the proxy but binkw32_orig.dll is missing" >&2; exit 1; }
put binkw32.dll; put BinkProxy.ini

if [ -f "$game/dxvk.conf" ] && ! grep -qF "$DXVK_MARKER" "$game/dxvk.conf"; then
    echo "  dxvk.conf skipped: there is one already that this package did not write"
else
    put dxvk.conf
fi

# ------------------------------------------------------------------ bloom

if [ "$bloom" = 1 ]; then
    echo "bloom -> $BLOOM"
    case "$BLOOM" in *' '*|*'#'*) echo "vkBasalt cannot read a path with a space or '#': $BLOOM" >&2; exit 1 ;; esac
    mkdir -p "$BLOOM/Shaders" "$BLOOM/Textures"
    # The shaders are not ours to redistribute, so they come from upstream, pinned by
    # commit and checked by hash: <sha256> <commit> <file>.
    while read -r sum commit file; do
        [ -n "$sum" ] || continue
        dst="$BLOOM/Shaders/$file"
        if ! echo "$sum  $dst" | sha256sum --quiet -c - >/dev/null 2>&1; then
            url="https://raw.githubusercontent.com/crosire/reshade-shaders/$commit/Shaders/$file"
            if command -v curl >/dev/null; then curl -fsSL -o "$dst" "$url"; else wget -qO "$dst" "$url"; fi
            echo "$sum  $dst" | sha256sum --quiet -c - || { echo "download does not match: $file" >&2; exit 1; }
        fi
        echo "  Shaders/$file"
    done < "$here/bloom/shaders.txt"
    cp "$here/bloom/A2Bloom.fx" "$BLOOM/A2Bloom.fx"
    sed -e "s|@BLOOM@|$BLOOM|g" -e "1i$BLOOM_MARKER" "$here/bloom/vkBasalt.conf.in" > "$BLOOM/vkBasalt.conf"
    echo "  vkBasalt.conf"

    # A 32-bit vkBasalt layer has to be installed for the game (a 32-bit process) to load
    # it: lib32-vkbasalt on Arch, or build it (postfx/vkbasalt/build.sh in the repository).
    layer=0
    for d in "${XDG_DATA_HOME:-$HOME/.local/share}/vulkan/implicit_layer.d" \
             /etc/vulkan/implicit_layer.d /usr/share/vulkan/implicit_layer.d; do
        ls "$d"/*[Bb]asalt*.json >/dev/null 2>&1 && layer=1
    done
    [ "$layer" = 1 ] || echo "  WARNING: no vkBasalt layer found -- install a 32-bit vkBasalt (lib32-vkbasalt on Arch)"
fi

# ------------------------------------------------------------------ what is left

loader=$(ls "$game/winmm.dll" "$game/dinput8.dll" 2>/dev/null | head -1 || true)
echo
[ -n "$loader" ] || echo "WARNING: no ASI loader (winmm.dll) in the game directory -- the plugins will not load."
echo "In the launcher (Heroic: Game settings -> Advanced -> Environment variables; Steam:"
echo "launch options, then %command%), set:"
echo "    WINEDLLOVERRIDES=winmm=n,b"
if [ "$bloom" = 1 ]; then
    echo "    ENABLE_VKBASALT=1"
    echo "    VKBASALT_CONFIG_FILE=$BLOOM/vkBasalt.conf"
    echo "Home toggles bloom in game."
fi
echo "Uninstall: $0 --uninstall \"$game\""
