<#
Armada II Refit -- install the release package into the game, on Windows.

  install.bat [<game dir>]                 install the plugins and dxvk.conf
  install.bat -Bloom [<game dir>]          also put the bloom preset in for ReShade
  install.bat -Uninstall [<game dir>]      take all of it out again

  -Msaa / -NoMsaa   MSAA.asi is installed only when a d3d8.dll (DXVK) is in the game
                    directory -- without DXVK the minimap goes black; these override

The game directory is the one holding Armada2.exe: the argument, else this folder's
parent if the package was unzipped into the game, else the GOG install found in the
registry, else it asks. PowerShell 5.1 or later; install.bat runs it.
#>
param(
    [string]$GameDir = "",
    [switch]$Bloom,
    [switch]$Uninstall,
    [switch]$Msaa,
    [switch]$NoMsaa
)
$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$DxvkMarker = "# generated by tools/renderer-config.sh"   # dxvk.conf files we wrote

function Test-Game([string]$d) { $d -and (Test-Path -LiteralPath (Join-Path $d "Armada2.exe")) }

if (-not (Test-Game $GameDir)) {
    if ($GameDir) { throw "no Armada2.exe in $GameDir" }
    $parent = Split-Path -Parent $here
    if (Test-Game $parent) { $GameDir = $parent }
}
if (-not $GameDir) {
    foreach ($k in @("HKLM:\SOFTWARE\WOW6432Node\GOG.com\Games", "HKLM:\SOFTWARE\GOG.com\Games")) {
        if (-not (Test-Path $k)) { continue }
        foreach ($g in Get-ChildItem $k) {
            $p = Get-ItemProperty $g.PSPath
            if ($p.gameName -like "*Armada II*" -and (Test-Game $p.path)) { $GameDir = $p.path; break }
        }
        if ($GameDir) { break }
    }
}
if (-not $GameDir) { $GameDir = (Read-Host "Game directory (the folder with Armada2.exe)").Trim('"') }
if (-not (Test-Game $GameDir)) { throw "no Armada2.exe in $GameDir" }
$GameDir = (Resolve-Path -LiteralPath $GameDir).Path

if (Get-Process -Name armada2 -ErrorAction SilentlyContinue) { throw "Armada2.exe is running -- quit the game first" }

function G([string]$n) { Join-Path $GameDir $n }
function Test-Proxy([string]$f) {
    (Test-Path -LiteralPath $f) -and (Select-String -LiteralPath $f -Pattern "BinkProxy" -SimpleMatch -Quiet)
}
function Test-OurDxvkConf {
    (Test-Path -LiteralPath (G "dxvk.conf")) -and
        (Select-String -LiteralPath (G "dxvk.conf") -Pattern $DxvkMarker -SimpleMatch -Quiet)
}

# ------------------------------------------------------------------ uninstall

if ($Uninstall) {
    foreach ($n in "HUD", "Menus", "MSAA") {
        foreach ($e in ".asi", ".ini", ".log") { Remove-Item -LiteralPath (G "$n$e") -ErrorAction SilentlyContinue }
    }
    if (Test-Proxy (G "binkw32.dll")) {
        if (Test-Path -LiteralPath (G "binkw32.dll.a2neb-backup")) {
            Move-Item -LiteralPath (G "binkw32.dll.a2neb-backup") (G "binkw32.dll") -Force
            Remove-Item -LiteralPath (G "binkw32_orig.dll") -ErrorAction SilentlyContinue
        } elseif (Test-Path -LiteralPath (G "binkw32_orig.dll")) {
            Move-Item -LiteralPath (G "binkw32_orig.dll") (G "binkw32.dll") -Force
        } else {
            Write-Warning "binkw32.dll is the proxy and there is no stock copy -- restore it by hand"
        }
    }
    foreach ($n in "BinkProxy.ini", "BinkProxy.log", "A2Bloom.ini") { Remove-Item -LiteralPath (G $n) -ErrorAction SilentlyContinue }
    if (Test-OurDxvkConf) { Remove-Item -LiteralPath (G "dxvk.conf") }
    Write-Host "uninstalled from $GameDir"
    exit 0
}

# ------------------------------------------------------------------ plugins

foreach ($line in Get-Content -LiteralPath (Join-Path $here "SHA256SUMS")) {
    $sum, $file = $line -split "\s+\*?", 2
    if ((Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $here $file)).Hash -ne $sum) {
        throw "the package is damaged: $file does not match SHA256SUMS"
    }
}
Write-Host "installing into $GameDir"

# A changed .ini is kept beside the new one, as <name>.ini.bak.
function Put([string]$f) {
    $src = Join-Path $here "game\$f"; $dst = G $f
    if ($f.EndsWith(".ini") -and (Test-Path -LiteralPath $dst) -and
        (Get-FileHash -LiteralPath $src).Hash -ne (Get-FileHash -LiteralPath $dst).Hash) {
        Copy-Item -LiteralPath $dst "$dst.bak" -Force
        Write-Host "  kept your old $f as $f.bak"
    }
    Copy-Item -LiteralPath $src $dst -Force
    Write-Host "  $f"
}

Put "HUD.asi"; Put "HUD.ini"
foreach ($n in "MenuScale.asi", "MenuScale.ini") { Remove-Item -LiteralPath (G $n) -ErrorAction SilentlyContinue }   # Menus.asi's old name
Put "Menus.asi"; Put "Menus.ini"

$withMsaa = Test-Path -LiteralPath (G "d3d8.dll")
if ($Msaa) { $withMsaa = $true }
if ($NoMsaa) { $withMsaa = $false }
if ($withMsaa) {
    Put "MSAA.asi"; Put "MSAA.ini"
} else {
    Remove-Item -LiteralPath (G "MSAA.asi") -ErrorAction SilentlyContinue
    Write-Host "  MSAA.asi skipped: no d3d8.dll (DXVK) in the game directory (-Msaa overrides)"
}

# The proxy forwards every call to the stock DLL as binkw32_orig.dll.
if (-not (Test-Proxy (G "binkw32.dll"))) {
    if (-not (Test-Path -LiteralPath (G "binkw32.dll"))) { throw "no binkw32.dll in $GameDir" }
    Copy-Item -LiteralPath (G "binkw32.dll") (G "binkw32.dll.a2neb-backup") -Force
    Copy-Item -LiteralPath (G "binkw32.dll") (G "binkw32_orig.dll") -Force
}
if (-not (Test-Path -LiteralPath (G "binkw32_orig.dll"))) { throw "binkw32.dll is the proxy but binkw32_orig.dll is missing" }
Put "binkw32.dll"; Put "BinkProxy.ini"

if ((Test-Path -LiteralPath (G "dxvk.conf")) -and -not (Test-OurDxvkConf)) {
    Write-Host "  dxvk.conf skipped: there is one already that this package did not write"
} else {
    Put "dxvk.conf"
}

# ------------------------------------------------------------------ bloom

if ($Bloom) {
    # ReShade finds its shaders in reshade-shaders\Shaders beside the game. They are not
    # ours to redistribute, so any that are missing come from upstream, pinned by commit
    # and checked by hash; ones already there (ReShade's own) are left alone.
    $sh = G "reshade-shaders\Shaders"
    New-Item -ItemType Directory -Force -Path $sh | Out-Null
    foreach ($line in Get-Content -LiteralPath (Join-Path $here "bloom\shaders.txt")) {
        if (-not $line.Trim()) { continue }
        $sum, $commit, $file = $line -split "\s+"
        $dst = Join-Path $sh $file
        if (Test-Path -LiteralPath $dst) { Write-Host "  reshade-shaders\Shaders\$file (already there)"; continue }
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -UseBasicParsing -OutFile $dst `
            -Uri "https://raw.githubusercontent.com/crosire/reshade-shaders/$commit/Shaders/$file"
        if ((Get-FileHash -Algorithm SHA256 -LiteralPath $dst).Hash -ne $sum) {
            Remove-Item -LiteralPath $dst; throw "download does not match: $file"
        }
        Write-Host "  reshade-shaders\Shaders\$file"
    }
    Copy-Item -LiteralPath (Join-Path $here "bloom\A2Bloom.ini") (G "A2Bloom.ini") -Force
    Write-Host "  A2Bloom.ini"
    if (-not (Get-ChildItem -LiteralPath $GameDir -Filter "ReShade*.ini" | Where-Object Name -ne "ReShadePreset.ini")) {
        Write-Host ""
        Write-Host "Bloom needs ReShade (reshade.me) installed for Armada2.exe -- for Vulkan when DXVK is"
        Write-Host "in the game directory. Then open its overlay (Home) and pick the A2Bloom.ini preset."
    } else {
        Write-Host "In ReShade's overlay (Home), pick the A2Bloom.ini preset."
    }
}

# ------------------------------------------------------------------ what is left

Write-Host ""
if (-not (Test-Path -LiteralPath (G "winmm.dll"))) {
    Write-Warning "no ASI loader (winmm.dll) in the game directory -- the plugins will not load."
}
Write-Host "Uninstall: install.bat -Uninstall `"$GameDir`""
