<#
Armada II Refit -- install the release package into the game, on Windows.

  install.bat [<game dir>]                 install
  install.bat -Uninstall [<game dir>]      take all of it out again

No choices to make: what can work here is installed, the rest is skipped and says why.
First the prerequisites (prereqs.txt: the ASI loader with STA2WidescreenPatch), bundled in
vendor\, each file only if it is missing. MSAA.asi goes in when DXVK is in the game
directory -- its d3d8.dll, or crosire's d3d8to9 on its d3d9.dll; without DXVK the
minimap goes black. The bloom preset goes in when ReShade is installed for the game;
installing ReShade is optional and by hand (README.txt), then run this again.

The game directory is the one holding Armada2.exe: the argument, else this folder's
parent if the package was unzipped into the game, else the GOG install found in the
registry, else it asks. PowerShell 5.1 or later; install.bat runs it.
#>
param(
    [string]$GameDir = "",
    [switch]$Uninstall
)
$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$DxvkMarker = "# generated by tools/renderer-config.sh"   # dxvk.conf files we wrote

function Test-Game([string]$d) { $d -and (Test-Path -LiteralPath (Join-Path $d "Armada2.exe")) }

if (-not (Test-Game $GameDir)) {
    if ($GameDir) { throw "no Armada2.exe in $GameDir" }
    $parent = Split-Path -Parent $here
    if (Test-Game $parent) { $GameDir = $parent }
}
if (-not $GameDir) {
    foreach ($k in @("HKLM:\SOFTWARE\WOW6432Node\GOG.com\Games", "HKLM:\SOFTWARE\GOG.com\Games")) {
        if (-not (Test-Path $k)) { continue }
        foreach ($g in Get-ChildItem $k) {
            $p = Get-ItemProperty $g.PSPath
            if ($p.gameName -like "*Armada II*" -and (Test-Game $p.path)) { $GameDir = $p.path; break }
        }
        if ($GameDir) { break }
    }
}
if (-not $GameDir) { $GameDir = (Read-Host "Game directory (the folder with Armada2.exe)").Trim('"') }
if (-not (Test-Game $GameDir)) { throw "no Armada2.exe in $GameDir" }
$GameDir = (Resolve-Path -LiteralPath $GameDir).Path

if (Get-Process -Name armada2 -ErrorAction SilentlyContinue) { throw "Armada2.exe is running -- quit the game first" }

function G([string]$n) { Join-Path $GameDir $n }
$Manifest = G "armada2-refit-prereqs.txt"   # what the prerequisites step added
function Get-Sha([string]$f) { (Get-FileHash -Algorithm SHA256 -LiteralPath $f).Hash.ToLower() }
# DXVK by content, never by name: GOG puts a d3d8.dll there too.
function Test-Dxvk([string]$f) {
    (Test-Path -LiteralPath $f) -and
        ([Text.Encoding]::ASCII.GetString([IO.File]::ReadAllBytes($f)) -match "(?i)dxvk")
}
# crosire's d3d8to9 1.16.0, as the repository's ./install places it (platform/vendor/), by hash.
function Test-D3d8to9([string]$f) {
    (Test-Path -LiteralPath $f) -and ((Get-Sha $f) -eq "122928cfe225c25d30decf7184a5d37e490cecf3b58256ba3206c7e1853f8ab8")
}
# DXVK in the chain: its own d3d8, or d3d8to9 in front of its d3d9.
function Test-DxvkChain {
    (Test-Dxvk (G "d3d8.dll")) -or ((Test-D3d8to9 (G "d3d8.dll")) -and (Test-Dxvk (G "d3d9.dll")))
}
function Test-Proxy([string]$f) {
    (Test-Path -LiteralPath $f) -and (Select-String -LiteralPath $f -Pattern "BinkProxy" -SimpleMatch -Quiet)
}
function Test-OurDxvkConf {
    (Test-Path -LiteralPath (G "dxvk.conf")) -and
        (Select-String -LiteralPath (G "dxvk.conf") -Pattern $DxvkMarker -SimpleMatch -Quiet)
}

# ------------------------------------------------------------------ uninstall

if ($Uninstall) {
    foreach ($n in "HUD", "Menus", "MSAA", "QOL", "Lighting", "Sky", "Online") {
        foreach ($e in ".asi", ".ini", ".log") { Remove-Item -LiteralPath (G "$n$e") -ErrorAction SilentlyContinue }
    }
    # The sky recipes this package put in Sky\; anything else there is the player's.
    if (Test-Path -LiteralPath (G "Sky")) {
        foreach ($r in Get-ChildItem -LiteralPath (Join-Path $here "sky") -Filter *.ini) {
            Remove-Item -LiteralPath (Join-Path (G "Sky") $r.Name) -ErrorAction SilentlyContinue
        }
        if (-not (Get-ChildItem -LiteralPath (G "Sky"))) { Remove-Item -LiteralPath (G "Sky") }
    }
    if (Test-Proxy (G "binkw32.dll")) {
        if (Test-Path -LiteralPath (G "binkw32.dll.a2neb-backup")) {
            Move-Item -LiteralPath (G "binkw32.dll.a2neb-backup") (G "binkw32.dll") -Force
            Remove-Item -LiteralPath (G "binkw32_orig.dll") -ErrorAction SilentlyContinue
        } elseif (Test-Path -LiteralPath (G "binkw32_orig.dll")) {
            Move-Item -LiteralPath (G "binkw32_orig.dll") (G "binkw32.dll") -Force
        } else {
            Write-Warning "binkw32.dll is the proxy and there is no stock copy -- restore it by hand"
        }
    }
    # ReShadePreset.ini only if it is still ours, unchanged.
    if ((Test-Path -LiteralPath (G "ReShadePreset.ini")) -and
        (Get-FileHash -LiteralPath (G "ReShadePreset.ini")).Hash -eq (Get-FileHash -LiteralPath (Join-Path $here "bloom\A2Bloom.ini")).Hash) {
        Remove-Item -LiteralPath (G "ReShadePreset.ini")
    }
    foreach ($n in "BinkProxy.ini", "BinkProxy.log", "A2Bloom.ini") { Remove-Item -LiteralPath (G $n) -ErrorAction SilentlyContinue }
    if (Test-OurDxvkConf) { Remove-Item -LiteralPath (G "dxvk.conf") }
    # The prerequisites, newest record first; a file changed since is left, and said so.
    if (Test-Path -LiteralPath $Manifest) {
        $records = @(Get-Content -LiteralPath $Manifest)
        [array]::Reverse($records)
        foreach ($r in $records) {
            $f, $sum = $r -split " "
            if (-not (Test-Path -LiteralPath (G $f))) { continue }
            if ((Get-Sha (G $f)) -ne $sum) { Write-Host "  left ${f}: it changed since it was installed"; continue }
            Remove-Item -LiteralPath (G $f)
        }
        Remove-Item -LiteralPath $Manifest
    }
    Write-Host "uninstalled from $GameDir"
    exit 0
}

foreach ($line in Get-Content -LiteralPath (Join-Path $here "SHA256SUMS")) {
    $sum, $file = $line -split "\s+\*?", 2
    if ((Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $here $file)).Hash -ne $sum) {
        throw "the package is damaged: $file does not match SHA256SUMS"
    }
}
Write-Host "installing into $GameDir"

# ------------------------------------------------------------------ prerequisites

# The ASI loader and STA2WidescreenPatch (prereqs.txt), in vendor\<name>\ because their
# licence allows it. A file already in the game directory is never overwritten. What this
# adds is recorded in $Manifest with its hash, so -Uninstall takes out only that, and
# only unchanged.
Write-Host "prerequisites:"
foreach ($line in Get-Content -LiteralPath (Join-Path $here "prereqs.txt")) {
    if (-not $line.Trim()) { continue }
    $name, $ver, $author, $lic, $page, $files = $line -split "\|"
    $files = $files -split " "
    if (Test-Path -LiteralPath (G $files[0])) { Write-Host "  ${name}: already installed"; continue }
    foreach ($f in $files) {
        if (-not (Test-Path -LiteralPath (G $f))) {
            Copy-Item -LiteralPath (Join-Path $here "vendor\$name\$f") (G $f)
            Add-Content -LiteralPath $Manifest "$f $(Get-Sha (G $f))"
        }
    }
    Write-Host "  $name $ver -- $author; $lic"
    Write-Host "      from $page"
}

# STA2WidescreenPatch.asi needs Microsoft's Visual C++ runtime (VCRUNTIME140.dll), which
# almost every Windows has. Installing it takes administrator rights and an unpinned
# Microsoft download, so this only says where to get it.
$sysdir = if ([Environment]::Is64BitOperatingSystem) { "SysWOW64" } else { "System32" }
if (-not (Test-Path -LiteralPath (Join-Path $env:WINDIR "$sysdir\vcruntime140.dll"))) {
    Write-Warning ("the Visual C++ runtime (x86) is missing, and the widescreen patch needs it. " +
        "Install it from https://aka.ms/vs/17/release/vc_redist.x86.exe")
}
Write-Host "the mod:"

# ------------------------------------------------------------------ plugins

# A changed .ini is kept beside the new one, as <name>.ini.bak.
function Put([string]$f) {
    $src = Join-Path $here "game\$f"; $dst = G $f
    if ($f.EndsWith(".ini") -and (Test-Path -LiteralPath $dst) -and
        (Get-FileHash -LiteralPath $src).Hash -ne (Get-FileHash -LiteralPath $dst).Hash) {
        Copy-Item -LiteralPath $dst "$dst.bak" -Force
        Write-Host "  kept your old $f as $f.bak"
    }
    Copy-Item -LiteralPath $src $dst -Force
    Write-Host "  $f"
}

Put "HUD.asi"; Put "HUD.ini"
foreach ($n in "MenuScale.asi", "MenuScale.ini") { Remove-Item -LiteralPath (G $n) -ErrorAction SilentlyContinue }   # Menus.asi's old name
Put "Menus.asi"; Put "Menus.ini"
Put "QOL.asi"; Put "QOL.ini"
Put "Online.asi"; Put "Online.ini"
# Lit per pixel in shaders only behind crosire's d3d8to9; per vertex on any other d3d8.
Put "Lighting.asi"; Put "Lighting.ini"
if (-not (Test-D3d8to9 (G "d3d8.dll"))) {
    Write-Host "  (Lighting: per vertex here -- its shaders need crosire's d3d8to9 as d3d8.dll)"
}
# The sky drawn from a recipe per map, in a shader; also only behind crosire's d3d8to9,
# and the stock sky anywhere else. The recipes go in Sky\, one per sky name.
Put "Sky.asi"; Put "Sky.ini"
New-Item -ItemType Directory -Force -Path (G "Sky") | Out-Null
$recipes = @(Get-ChildItem -LiteralPath (Join-Path $here "sky") -Filter *.ini)
foreach ($r in $recipes) { Copy-Item -LiteralPath $r.FullName (Join-Path (G "Sky") $r.Name) -Force }
Write-Host "  Sky\: $($recipes.Count) sky recipes"
if (-not (Test-D3d8to9 (G "d3d8.dll"))) {
    Write-Host "  (Sky: the stock sky here -- the procedural one needs crosire's d3d8to9 as d3d8.dll)"
}

if (Test-DxvkChain) {
    Put "MSAA.asi"; Put "MSAA.ini"
} else {
    Remove-Item -LiteralPath (G "MSAA.asi") -ErrorAction SilentlyContinue
    Write-Host "  MSAA.asi skipped: DXVK is not in the game directory"
}

# The proxy forwards every call to the stock DLL as binkw32_orig.dll.
if (-not (Test-Proxy (G "binkw32.dll"))) {
    if (-not (Test-Path -LiteralPath (G "binkw32.dll"))) { throw "no binkw32.dll in $GameDir" }
    Copy-Item -LiteralPath (G "binkw32.dll") (G "binkw32.dll.a2neb-backup") -Force
    Copy-Item -LiteralPath (G "binkw32.dll") (G "binkw32_orig.dll") -Force
}
if (-not (Test-Path -LiteralPath (G "binkw32_orig.dll"))) { throw "binkw32.dll is the proxy but binkw32_orig.dll is missing" }
Put "binkw32.dll"; Put "BinkProxy.ini"

if ((Test-Path -LiteralPath (G "dxvk.conf")) -and -not (Test-OurDxvkConf)) {
    Write-Host "  dxvk.conf skipped: there is one already that this package did not write"
} else {
    Put "dxvk.conf"
}

# ------------------------------------------------------------------ bloom

# Only when ReShade is installed for the game: its setup leaves ReShade.ini beside the
# exe, and it finds shaders in reshade-shaders\Shaders there. They are not ours to
# redistribute, so any that are missing come from upstream, pinned by commit and checked
# by hash; ones already there (ReShade's own) are left alone. Bloom is optional: a
# failure skips it.
function Install-Bloom {
    $sh = G "reshade-shaders\Shaders"
    New-Item -ItemType Directory -Force -Path $sh | Out-Null
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    foreach ($line in Get-Content -LiteralPath (Join-Path $here "bloom\shaders.txt")) {
        if (-not $line.Trim()) { continue }
        $sum, $commit, $file = $line -split "\s+"
        $dst = Join-Path $sh $file
        if (Test-Path -LiteralPath $dst) { continue }
        $url = "https://raw.githubusercontent.com/crosire/reshade-shaders/$commit/Shaders/$file"
        Invoke-WebRequest -UseBasicParsing -OutFile $dst -Uri $url
        if ((Get-FileHash -Algorithm SHA256 -LiteralPath $dst).Hash -ne $sum) {
            Remove-Item -LiteralPath $dst; throw "download does not match: $file"
        }
    }
    Copy-Item -LiteralPath (Join-Path $here "bloom\A2Bloom.ini") (G "A2Bloom.ini") -Force
    # ReShade loads ReShadePreset.ini unless told otherwise, so with no preset of the
    # player's own, ours takes that name and bloom needs no step in the overlay.
    if (-not (Test-Path -LiteralPath (G "ReShadePreset.ini"))) {
        Copy-Item -LiteralPath (G "A2Bloom.ini") (G "ReShadePreset.ini")
        return $true
    }
    return $false
}
if (-not (Test-Path -LiteralPath (G "ReShade.ini"))) {
    Write-Host "  bloom skipped: ReShade is not installed (optional -- README.txt)"
} else {
    try {
        if (Install-Bloom) {
            Write-Host "  bloom, as ReShade's preset (ReShadePreset.ini)"
        } else {
            Write-Host "  A2Bloom.ini -- you have a ReShade preset already; pick this one in its overlay"
        }
    } catch {
        Write-Host "  bloom skipped: $($_.Exception.Message)"
    }
}

# ------------------------------------------------------------------ what is left

Write-Host ""
if (-not (Test-Path -LiteralPath (G "winmm.dll"))) {
    Write-Warning "no ASI loader (winmm.dll) in the game directory -- the plugins will not load."
}
Write-Host "Uninstall: install.bat -Uninstall `"$GameDir`""
