#!/usr/bin/env bash
# Compile HLSL into shader bytecode embedded in a C header, for a plugin that draws
# through the Direct3D 9 device behind the game's (platform/D3D9.md, d3d9dev.h).
#
#   hlsl.sh <out.h> <file.hlsl> <entry>:<profile>:<symbol> [...]
#
# Each entry point becomes `static const unsigned long <symbol>[]`, legacy (d3dbc)
# bytecode ready for CreateVertexShader/CreatePixelShader; no compiler is needed at
# run time. The compiler is vkd3d's (Arch: vkd3d), whose output is correct but not
# optimised.
#
# The header is committed beside its .hlsl, stamped with the sha256 of the .hlsl and
# of the entry list, so a plugin builds where vkd3d is missing or too old (CI's
# Ubuntu): the header is rewritten only when the stamp no longer matches, and with no
# compiler a matching header is kept and a stale one is an error.
set -euo pipefail
[ $# -ge 3 ] || { sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; exit 2; }
out=$1 src=$2; shift 2
stamp="source $(cat "$src" <(printf '%s\n' "$@") | sha256sum | cut -d' ' -f1)"
if [ -f "$out" ] && grep -qF "$stamp" "$out"; then exit 0; fi
command -v vkd3d-compiler >/dev/null ||
    { echo "hlsl.sh: $out is stale and vkd3d-compiler is not installed (Arch: vkd3d)" >&2; exit 1; }
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
{
    echo "/* generated by platform/d3d9/hlsl.sh from $(basename "$src") -- do not edit"
    echo " * $stamp */"
    for spec in "$@"; do
        IFS=: read -r entry profile sym <<< "$spec"
        vkd3d-compiler -x hlsl -b d3dbc -p "$profile" -e "$entry" -o "$tmp/$sym.bin" "$src"
        [ $(( $(stat -c %s "$tmp/$sym.bin") % 4 )) = 0 ] ||
            { echo "hlsl.sh: $sym: bytecode is not whole tokens" >&2; exit 1; }
        echo "static const unsigned long $sym[] = {  /* $entry, $profile */"
        od -An -v -t x4 -w16 "$tmp/$sym.bin" | sed -E 's/ +([0-9a-f]{8})/ 0x\1,/g; s/^/   /'
        echo "};"
    done
} > "$tmp/out.h"
mv "$tmp/out.h" "$out"
echo "hlsl.sh: wrote $(basename "$out")"
